package br.gov.esocial.servicos.empregador.lote.eventos.envio.v1_1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18.redhat-1
 * 2016-05-06T12:10:44.502-03:00
 * Generated source version: 2.7.18.redhat-1
 * 
 */
@WebServiceClient(name = "ServicoEnviarLoteEventos", 
                  wsdlLocation = "file:/home/jpviragine/workspace91/PoCFuseTSE-eSocial/src/main/resources/WSDL/WsEnviarLoteEventos-v1_1_0.wsdl",
                  targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0") 
public class ServicoEnviarLoteEventos_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", "ServicoEnviarLoteEventos");
    public final static QName WsEnviarLoteEventos = new QName("http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", "WsEnviarLoteEventos");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/jpviragine/workspace91/PoCFuseTSE-eSocial/src/main/resources/WSDL/WsEnviarLoteEventos-v1_1_0.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicoEnviarLoteEventos_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/jpviragine/workspace91/PoCFuseTSE-eSocial/src/main/resources/WSDL/WsEnviarLoteEventos-v1_1_0.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicoEnviarLoteEventos_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicoEnviarLoteEventos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicoEnviarLoteEventos_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicoEnviarLoteEventos_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicoEnviarLoteEventos_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicoEnviarLoteEventos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServicoEnviarLoteEventos
     */
    @WebEndpoint(name = "WsEnviarLoteEventos")
    public ServicoEnviarLoteEventos getWsEnviarLoteEventos() {
        return super.getPort(WsEnviarLoteEventos, ServicoEnviarLoteEventos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicoEnviarLoteEventos
     */
    @WebEndpoint(name = "WsEnviarLoteEventos")
    public ServicoEnviarLoteEventos getWsEnviarLoteEventos(WebServiceFeature... features) {
        return super.getPort(WsEnviarLoteEventos, ServicoEnviarLoteEventos.class, features);
    }

}
