package br.gov.esocial.servicos.empregador.lote.eventos.envio.v1_1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18.redhat-1
 * 2016-05-06T12:10:44.472-03:00
 * Generated source version: 2.7.18.redhat-1
 * 
 */
@WebService(targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", name = "ServicoEnviarLoteEventos")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicoEnviarLoteEventos {

    @WebMethod(operationName = "EnviarLoteEventos", action = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0/ServicoEnviarLoteEventos/EnviarLoteEventos")
    @Action(input = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0/ServicoEnviarLoteEventos/EnviarLoteEventos", output = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0/ServicoEnviarLoteEventos/EnviarLoteEventosResponse")
    @RequestWrapper(localName = "EnviarLoteEventos", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", className = "br.gov.esocial.servicos.empregador.lote.eventos.envio.v1_1_0.EnviarLoteEventos")
    @ResponseWrapper(localName = "EnviarLoteEventosResponse", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", className = "br.gov.esocial.servicos.empregador.lote.eventos.envio.v1_1_0.EnviarLoteEventosResponse")
    @WebResult(name = "EnviarLoteEventosResult", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0")
    public br.gov.esocial.servicos.empregador.lote.eventos.envio.v1_1_0.EnviarLoteEventosResponse.EnviarLoteEventosResult enviarLoteEventos(
        @WebParam(name = "loteEventos", targetNamespace = "http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0")
        br.gov.esocial.servicos.empregador.lote.eventos.envio.v1_1_0.EnviarLoteEventos.LoteEventos loteEventos
    );
}
